### ISSUE TITLE
求完整BOM表采购清单

### ISSUE THREAD

**Issue by ming0713** [jinsonli/ElectronBot-Voice#1]
求完整BOM表采购清单，最好详细到采购链接，感谢！

**Comment by jinsonli** [comment]
我都是零零散散买的哦。 很多器件都是以前买的。 - - ！

**Comment by ming0713** [comment]
收到，谢谢你的回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 上午9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jinsonli/ElectronBot-Voice] 求完整BOM表采购清单 (Issue #1)





 
我都是零零散散买的哦。 很多器件都是以前买的。 - - ！

**Comment by shui1017** [comment]
> 

能发我一份吗？

**Comment by shui1017** [comment]
> 收到，谢谢你的回复
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月25日(星期一) 上午9:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jinsonli/ElectronBot-Voice] 求完整BOM表采购清单 (Issue #1) 我都是零零散散买的哦。 很多器件都是以前买的。 - - ！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以发我一份吗？
