### ISSUE TITLE
关于扬声器的选择

### ISSUE THREAD

**Issue by telland** [jinsonli/ElectronBot-Voice#8]
想问一下，关于扬声器的选择，除了大小上的需求，对于电阻的功率有没有要求

**Comment by jinsonli** [comment]
不能超过USB电源的功率， USB一般是 5V 500MA， 最大就是  2.5W，机器人本身有功耗、功放最大时 3W是可以满足要求的。
喇叭作为负载， 通常是8欧 1W， 当然大一点点也是可以的，只不过USB电源可能扛不住。

**Comment by telland** [comment]
感谢，还有一个问题
![image](https://user-images.githubusercontent.com/53437926/181591682-6ba78e34-cce3-4c05-a076-791252e418ea.png)
JLC 打板子的时候发现 I2C__SCL_1 这个布线有问题，想问下这个是没有使用所以不需要链接吗，还是说规则问题不用管
![image](https://user-images.githubusercontent.com/53437926/181592095-8011df8e-f685-45c1-a576-04dfbbc5c74c.png)
两块板子都有同样问题

**Comment by jinsonli** [comment]
有用到的。 我之前打板子没有碰到问题哈。 我看网友也打板了， 不过没有导入 立创EDA。&nbsp; &nbsp;直接上传的 pcb.zip




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jinsonli/ElectronBot-Voice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 凌晨0:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jinsonli/ElectronBot-Voice] 关于扬声器的选择 (Issue #8)





 
感谢，还有一个问题
 
 JLC 打板子的时候发现 I2C__SCL_1 这个布线有问题，想问下这个是没有使用所以不需要链接吗，还是说规则问题不用管
 
 两块板子都有同样问题

**Comment by telland** [comment]
解决了 AD 转JLC 的问题
